### ISSUE TITLE
незачет

### ISSUE THREAD

**Issue by lesyapisha** [Ulashyn/Ulashyn.github.io#1]
Исправить:
1. Не соответствие макету. Твой основной блок растянут на ширину экрана браузера, нужно ему задать размеры и выровнять по центру. (И тень не забудь, как в макете:) )
2. Ты реализовал линии отдельными блоками, у этих блоков заданы значения для margin впоследствии чего получилось вертикальное схлопывание марджинов, по отношению к соседним елементам (тут почитать что это http://xiper.net/learn/css/box-model/margin-collapsing). Это не критично, но в даном случае переделать используя border.
3. В качестве единиц измерения рекомендуеться использовать px или %.
4. \* Хочу смайлик розового цвета, который единажды увеличиваеться при наведении до 50px в диаметре.

**Comment by Ulashyn** [comment]
Виправлено
