### ISSUE TITLE
незачет дз3

### ISSUE THREAD

**Issue by lesyapisha** [Ulashyn/Ulashyn.github.io#4]
1. http://prntscr.com/8y3wwr  бага кросбраузерности в мозиле.
   Поскольку кроссбраузерность пока не требуется, можеш вернуться к этому, когда пройдете эту тему. 
2. Восстановление потока: http://prntscr.com/8y43ri  для li задан float, значение overflow:hidden задается родителю ul, у тебя задан для nav. Разберись еще раз как это работает.
3. После нажатия появляеться выделение, его не должно быть http://prntscr.com/8y4763, http://prntscr.com/8y47yd

**Comment by Ulashyn** [comment]
Homework 3 fixed
